apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: rustmq-prod
  annotations:
    config.kubernetes.io/description: "RustMQ production environment"

bases:
- ../../base

namespace: rustmq

namePrefix: prod-

commonLabels:
  environment: prod

images:
- name: us-docker.pkg.dev/PROJECT_ID/rustmq/rustmq-controller
  newName: us-docker.pkg.dev/PROJECT_ID/rustmq/rustmq-controller
  newTag: v1.0.0  # Production uses specific version tags
- name: us-docker.pkg.dev/PROJECT_ID/rustmq/rustmq-broker
  newName: us-docker.pkg.dev/PROJECT_ID/rustmq/rustmq-broker
  newTag: v1.0.0
- name: us-docker.pkg.dev/PROJECT_ID/rustmq/rustmq-admin-server
  newName: us-docker.pkg.dev/PROJECT_ID/rustmq/rustmq-admin-server
  newTag: v1.0.0

configMapGenerator:
- name: rustmq-broker-config
  behavior: merge
  literals:
  - gcs_bucket=rustmq-production-messages

patchesStrategicMerge:
- patches/controller-patch.yaml
- patches/broker-patch.yaml
- patches/hpa-patch.yaml
- patches/serviceaccount-patch.yaml
- patches/security-patch.yaml
