apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rustmq

resources:
- deployment.yaml
- service.yaml
- configmap.yaml
- ingress.yaml

commonLabels:
  app.kubernetes.io/name: rustmq
  app.kubernetes.io/component: webui
  app.kubernetes.io/managed-by: kustomize

configMapGenerator:
- name: rustmq-webui-config
  literals:
  - RUSTMQ_ENV=production
  behavior: merge

images:
- name: us-docker.pkg.dev/PROJECT_ID/rustmq/rustmq-webui
  newTag: latest
