apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: rustmq-broker
  namespace: rustmq
  labels:
    app.kubernetes.io/name: rustmq
    app.kubernetes.io/component: broker-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: rustmq-broker
  minReplicas: 2  # Will be overridden by overlay
  maxReplicas: 10  # Will be overridden by overlay
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300  # 5 minutes
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60  # Scale down max 50% per minute
    scaleUp:
      stabilizationWindowSeconds: 60  # 1 minute
      policies:
      - type: Percent
        value: 100
        periodSeconds: 60  # Scale up max 100% per minute
      - type: Pods
        value: 4
        periodSeconds: 60  # Or add max 4 pods per minute
      selectPolicy: Max
