apiVersion: v1
kind: Service
metadata:
  name: rustmq-admin-server
  namespace: rustmq
  labels:
    app.kubernetes.io/name: rustmq
    app.kubernetes.io/component: admin-server
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: rustmq
    app.kubernetes.io/component: admin-server
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
