# External Secrets Operator - ExternalSecret Resources
# Phase 2: Configuration Management (October 2025)
#
# These ExternalSecrets sync from Google Secret Manager to Kubernetes Secrets
# Actual secret values are stored securely in Google Secret Manager

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: rustmq-tls-cert
  namespace: rustmq
  labels:
    app.kubernetes.io/name: rustmq
    app.kubernetes.io/component: tls-certificate
spec:
  # Refresh interval - sync from Secret Manager every 1 hour
  refreshInterval: 1h

  # Reference to SecretStore
  secretStoreRef:
    name: rustmq-secret-store
    kind: SecretStore

  # Target Kubernetes Secret
  target:
    name: rustmq-tls-cert
    creationPolicy: Owner
    template:
      type: kubernetes.io/tls
      data:
        tls.crt: "{{ .cert | b64dec }}"
        tls.key: "{{ .key | b64dec }}"
        ca.crt: "{{ .ca | b64dec }}"

  # Data to fetch from Google Secret Manager
  data:
    - secretKey: cert
      remoteRef:
        key: ${TLS_CERT_SECRET_NAME}
    - secretKey: key
      remoteRef:
        key: ${TLS_KEY_SECRET_NAME}
    - secretKey: ca
      remoteRef:
        key: ${TLS_CA_SECRET_NAME}

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: rustmq-gcs-credentials
  namespace: rustmq
  labels:
    app.kubernetes.io/name: rustmq
    app.kubernetes.io/component: gcs-credentials
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: rustmq-secret-store
    kind: SecretStore

  target:
    name: rustmq-gcs-credentials
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        credentials.json: "{{ .credentials | b64dec }}"

  data:
    - secretKey: credentials
      remoteRef:
        key: ${GCS_CREDENTIALS_SECRET_NAME}

---
# Example: Admin API Key secret
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: rustmq-admin-api-key
  namespace: rustmq
  labels:
    app.kubernetes.io/name: rustmq
    app.kubernetes.io/component: admin-api-key
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: rustmq-secret-store
    kind: SecretStore

  target:
    name: rustmq-admin-api-key
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        api-key: "{{ .apikey }}"

  data:
    - secretKey: apikey
      remoteRef:
        key: rustmq-${ENVIRONMENT}-admin-api-key
        # Version (optional, defaults to latest)
        version: latest
