# External Secrets Operator - SecretStore Configuration
# Phase 2: Configuration Management (October 2025)
#
# This SecretStore connects External Secrets Operator to Google Secret Manager
# using Workload Identity for secure, keyless authentication.
#
# Google Cloud native integration:
# - Google Secret Manager as secret backend
# - Workload Identity for authentication (no keys!)
# - Regional replication for reliability

apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: rustmq-secret-store
  namespace: rustmq
  labels:
    app.kubernetes.io/name: rustmq
    app.kubernetes.io/component: secret-store
    app.kubernetes.io/managed-by: external-secrets-operator
spec:
  provider:
    gcpsm:
      # GCP Project ID (will be set via Kustomize overlay)
      projectID: ${GCP_PROJECT_ID}

      # Authentication using Workload Identity (no service account keys!)
      auth:
        workloadIdentity:
          clusterLocation: ${GCP_REGION}
          clusterName: ${CLUSTER_NAME}
          serviceAccountRef:
            name: rustmq-sa

---
# ClusterSecretStore for cluster-wide secret access (optional)
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: rustmq-cluster-secret-store
  labels:
    app.kubernetes.io/name: rustmq
    app.kubernetes.io/component: cluster-secret-store
    app.kubernetes.io/managed-by: external-secrets-operator
spec:
  provider:
    gcpsm:
      projectID: ${GCP_PROJECT_ID}
      auth:
        workloadIdentity:
          clusterLocation: ${GCP_REGION}
          clusterName: ${CLUSTER_NAME}
          serviceAccountRef:
            name: rustmq-sa
            namespace: rustmq
