apiVersion: v1
kind: ConfigMap
metadata:
  name: controller-config
  namespace: rustmq
data:
  controller.toml: |
    [controller]
    id = "${HOSTNAME}"
    rack_id = "${ZONE}"
    
    [network]
    quic_listen = "0.0.0.0:9094"
    rpc_listen = "0.0.0.0:9095"
    admin_listen = "0.0.0.0:9642"
    
    [controller.raft]
    # Raft consensus configuration for production
    max_payload_entries = 300
    enable_tick = true
    enable_heartbeat = true
    heartbeat_timeout_ms = 2000
    election_timeout_ms = 5000
    append_entries_timeout_ms = 3000
    snapshot_policy = "LogsSinceLast(5000)"
    max_applied_log_to_keep = 1000
    purge_batch_size = 256
    
    # Performance optimizations
    enable_heartbeat_log = false
    enable_elect_log = false
    
    # Storage configuration
    [controller.storage]
    wal_dir = "/var/lib/rustmq/wal"
    snapshot_dir = "/var/lib/rustmq/snapshots"
    
    [object_storage]
    storage_type = { GCS = { bucket = "${GCS_BUCKET}" } }
    region = "${GCS_REGION}"
    
    [security]
    enabled = true
    default_auth_mode = "mTLS"
    ca_cert_path = "/etc/certs/ca.crt"
    cert_path = "/etc/certs/tls.crt"
    key_path = "/etc/certs/tls.key"
    
    [monitoring]
    prometheus_enabled = true
    prometheus_port = 9642
    log_level = "info"
    
    [performance]
    max_concurrent_requests = 1000
    request_timeout_ms = 30000
    connection_pool_size = 50