name: Release with SLSA Provenance

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      digests: ${{ steps.hash.outputs.digests }}

    steps:
      - uses: actions/checkout@v4

      - name: Build release binaries
        run: cargo build --release --bins

      - name: Package release artifacts
        run: |
          mkdir release
          cp target/release/rustmq-broker release/
          cp target/release/rustmq-controller release/
          cp target/release/rustmq-admin release/
          tar -czvf release.tar.gz release

      - name: Generate subject for provenance
        id: hash
        run: |
          set -euo pipefail
          echo "hashes=$(sha256sum release.tar.gz | base64 -w0)" >> "${GITHUB_OUTPUT}"

  provenance:
    needs: [build]
    permissions:
      actions: read
      id-token: write
      contents: write
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@v1.4.0
    with:
      base64-subjects: "${{ needs.build.outputs.digests }}"
      upload-assets: true